# Generated by Django 6.0.3 on 2026-08-21 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='images_archive',
            field=models.FileField(blank=True, upload_to='projects/archives/'),
        ),
        migrations.AddField(
            model_name='project',
            name='sections',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
